### ISSUE TITLE
Map search for the samples

### ISSUE THREAD

**Issue by paalge** [SIOS-Svalbard/Aen_sample#1]
There needs to be a way of searching for the samples within a area on the map. 
@ferrighi might have some ideas on how could be done. 
Openlayers 3 has support for generating areas, but need how to search with these in postgresql needs to be researched.

**Comment by ferrighi** [comment]
So you want to create a rectangle on the map and query postgres to give you back all samples tagged with lat/long coordinates which belong to that area?

**Comment by paalge** [comment]
Should be fixed by 21f031eca1c13d62d5ae5fd518dba12aea48d6a4

**Comment by paalge** [comment]
Finally fixed in f143d95
